### ISSUE TITLE
Google Search API - Result limit of 100 Results

### ISSUE THREAD

**Issue by viertel** [googleapis/google-api-php-client#1502]
Hello together,

I am using the Google Search API Client with PHP to create a custom search.
Is it possible to use the google search without an result limit? I get 4000 results for my search but I am only able to look into 100 of it via changing "start"-parameter. The payed version has still the result limit - right?
So what I can do to receive all results of my search?
The modification of lowRange and highRange parameter doesn't work. I added lowRange=101 and highRange=200 and get more than 100 results?! How does this parameters work?

Greetings,

**Comment by mattwhisenhunt** [comment]
It sounds like you are talking about the Custom Search JSON API. I'm not really connected to that product in any way. But I'm going to try to answer your questions albeit in a very unofficial capacity:
The 100 result limit is intentional. I think of CSE not as a data science tool but as a high level tool that helps you create great experiences for your audience quickly.
Right, the paid version does have that same limit.
Two approaches to getting more results occur off the top of my head: use a set of more specific queries that each result in less than 100 results; crawl the pages yourself, web crawlers are really fun projects.
Ranges are related to [filtering and sorting](https://developers.google.com/custom-search/docs/structured_search#restrict-to-range), which may be another way to chunk those 4000 results down to smaller parts. You will need to choose what field to restrict though.

**Comment by viertel** [comment]
Hello @mattwhisenhunt ,
first of all, thank you for your answer. You are right, I speak about the Custom Search JSON API. 
At the moment, I am already trying to find a web crawler which I can configure such that all subsites of a concrete link will be crawled. 

For example: 
The concrete URL is "https://www.nintendo.com/games/detail/super-mario-party-switch".
So my plan is to crawl all URLs starting with "https://www.nintendo.com/games/detail/" and containing "switch" in the last part of the URL. Which would be all pages for Switch games.

Do you have an idea how to do that? A code example for php would be nice.

Have a nice weekend.
Greetings, 
viertel

**Comment by mattwhisenhunt** [comment]
:fish: Short Answer:
https://github.com/spatie/crawler

🎣 Long Answer:
http://aosabook.org/en/500L/a-web-crawler-with-asyncio-coroutines.html
+
https://toys.lerdorf.com/archives/57-ZeroMQ-+-libevent-in-PHP.html

Gimme a holler if you have anymore questions.
