### ISSUE TITLE
Integrate Google Hotel Ads

### ISSUE THREAD

**Issue by stucchi** [googleapis/google-api-php-client#1525]
Successfully using this library with different products, I was looking for a class to integrate Google Hotel Ads, as defined at https://developers.google.com/hotels/hotel-ads/api-reference/v21/using-apis-v21

It looks like it's not there, maybe because this is not visible to all of the customers, you need to be a partner. Nonetheless, it would be great to allow the library to interact with Google Hotel Ads

**Comment by mattwhisenhunt** [comment]
I'm sorry it looks like this API is only available to authorized integration partners.
https://www.google.com/ads/hotels/find-a-partner/

**Comment by stucchi** [comment]
Yes @mattwhisenhunt you are right, but what if you work for one of them (I am, for example)... 
I am extending the library on my own, and it works perfectly, I'd love to speed up the development time for PHP users in my same situation. Is this a bad idea or it makes some sense for me to build something and share it, even if not everyone will be able to use it ?

**Comment by mattwhisenhunt** [comment]
I would say check your partner agreement to be sure.
All of our services for this library are generated from the same place as that reference you linked: another API called Discovery. Typically partners with access to a limited-access API also have access to the discovery doc. Sometimes the API team just generates client libraries and distributes those.

We don't merge PRs to the services repo because it is all auto-generated anyways.

I hope that answers your question, I'm not sure in what sense it might be a bad idea.
