### ISSUE TITLE
"vendor" subdirectory is missing in v2.2.1 and v2.2.2

### ISSUE THREAD

**Issue by tnt4brain** [googleapis/google-api-php-client#1563]
'Vendor' subdir is again missed starting since v2.2.1 (#1271 mentions the same issue).

Could you please change release script for subsequent versions back so it packs 'vendor' subdirectory into archives too?

**Comment by mattwhisenhunt** [comment]
This doesn't seem to have been an issue since June.
https://github.com/googleapis/google-api-php-client/releases/download/v2.2.2/google-api-php-client-2.2.2.zip
https://github.com/googleapis/google-api-php-client/releases/download/v2.2.1/google-api-php-client-2.2.1.zip
both have vendor directories. I need more detail about your problem to be able to help you solve it.

**Comment by striderman** [comment]
Looks like problem is still actual.
Releases page: https://github.com/googleapis/google-api-php-client/releases
Newest release link: https://github.com/googleapis/google-api-php-client/archive/v2.5.0.zip
there is no "vendor" directory in zip archive

**Comment by jdpedrie** [comment]
Thanks for the reminder @striderman. I've added the release packages.
