### ISSUE TITLE
Service Account authentication docs could use non-domain-wide example

### ISSUE THREAD

**Issue by robolmos** [googleapis/google-api-php-client#1571]
I think the service account authentication docs could benefit with a section for the scenario where it should only have access to specific items instead of domain-wide access. When attempting to do this, I discovered that a setScopes() call is necessary.

#### Steps to reproduce

1. Create a service account
2. Grant service account "view" access to a single Google Sheet via the email address
2. Follow the docs and example code here: https://developers.google.com/api-client-library/php/auth/service-accounts
3. Docs code indicates this:
```php
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
```
5. Error:

```
Fatal error: Uncaught exception 'Google_Service_Exception' with message '{
  "error": "invalid_scope",
  "error_description": "Empty or missing scope not allowed."
}'
```

I'm guessing this is because the service account wasn't granted domain-wide access.

#### Adding the missing setScopes() call

```php
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
// the missing line which resolves the error
$client->setScopes(Google_Service_Sheets::SPREADSHEETS_READONLY);
```

And now I'm able to access the specific sheet with only "view" access granted to it. Much more secure IMO.

**Comment by danielgsims** [comment]
Hi @robolmos. Thanks for sharing this with us!

I reviewed the doc for service account access that you shared. It sounds like your issue was specifically by using service account credentials while using sheets, but the documentation uses SQL Admin as an example. The rest of the usage is implied based on the specific service you're using.

When looking at the PHP Quick Start guide for the Sheets API, it covers requiring valid scope: https://developers.google.com/sheets/api/quickstart/php

I think cross referencing these docs covers how to use sheets with service account credentials, but I will pass this issue onto some others to see what they think! Thanks again.
