### ISSUE TITLE
China region can not use Google Docs API ?

### ISSUE THREAD

**Issue by zh7314** [googleapis/google-api-php-client#1590]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

2019/2/5 , i get email from google cloud ,i try to run example in php ，but i try many way it‘s still response 
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.googleapis.com:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
i change CURLOPT_SSLVERSION  but not work
china region  is not allow to access api？
or any way to fix it？

**Comment by jdpedrie** [comment]
Hi @zh7314,

Do calls to other Google APIs succeed? Are you sure it's specifically related to the Docs API rather than a client or application server misconfiguration?

If you've verified that the problem is specific to Docs, we are unfortunately not well positioned to assist with API problems. The team suggests using [Stackoverflow](https://stackoverflow.com/questions/tagged/google-docs-api) for technical assistance. You can also review the [How To Get Help](https://developers.google.com/docs/api/support) page on the Google Docs API support site.

**Comment by jdpedrie** [comment]
Please feel free to update and reopen if you are still having issues and have not had any luck with the support channels I shared.
