### ISSUE TITLE
Google_Client::verifyIdToken return invalid token signature 

### ISSUE THREAD

**Issue by jbduzan** [googleapis/google-api-php-client#161]
I'm trying to work with the php client of google Oauth2 api to validate an id_token. The id_token is provided by a javascript app on which the user login his google account, and i'm givin this token to my php api server, in order to validate it and retrieve the right informations from my bdd.

The login in javascript is successfull and the access and id_token seems right, but when I try to verify it with Google_Client->verifyIdToken()

$client = new Google_Client();
$ticket = $client->verifyIdToken(myToken);
, it return an invalid token signature exception (fail when trying to use the google cert to valid the token).

My first assumption was to think the token is not valid, so to make sur it is, i submited it to google validation url https://www.googleapis.com/oauth2/v1/tokeninfo?id_token=token

it return user info, so my token seems to be valid :

{
issuer: "accounts.google.com",
issued_to: "id",
audience: "id",
user_id: "id",
expires_in: 2149,
issued_at: 1397636222,
email: "mail",
verified_email: true
}
Tried everything i can think of, but can't solve this one. can someone help me ?

Question asked on stackoverflow too : http://stackoverflow.com/questions/23104721/google-oauth2-verifyidtoken-return-invalid-token-signature-with-valid-id-token

**Comment by NexProME** [comment]
It's timezone fault!
in my case it's work(day), not work(night after 12AM), work again(tomorrow)!
when it's stop working, just set timezone to America/New_York and its work, remove timezone then stop working.
And its happened because of some country have future date window rather than usA.
you know that if you change your system date time then SSL stop working.
I think it's the same problem. google sign it for it's own today but actually your yesterday!

php 7.1
macOS Sierra
Timezone 3:30

**Comment by doubleOrt** [comment]
Are you sure ? i just used both `date_default_timezone_set('America/Los_Angeles');` and `date_default_timezone_set('America/New_York');` and it's still not working. However, i can confirm that it does work during the day and stops working as darkness conquers the sky.

**Comment by doubleOrt** [comment]
@ianbarber Moving to `OpenSSL/1.0.2l` didn't fix the issue. What should i do now ?
