### ISSUE TITLE
Blank response on 4xx error

### ISSUE THREAD

**Issue by benderis** [googleapis/google-api-php-client#1616]
I having some trouble receiving 4xx error responses from google . It just won't return anything same code when it's succeed return 200 and connection id so I can save it in database for later use . I am using to create Interconnect attachments via api . So if there is error I want to show error to customers so they can send error to me . If I make those api calls via Insomnia and Postman google return 4xx error with message whats wrong . I have return $result; but still nothing empty page and there is nothing in server error logs .

**Comment by jdpedrie** [comment]
Please share a code sample so that we can determine whether the issue lies with the API, with this client, or with the code you're using to call the service.

**Comment by benderis** [comment]
here is code bellow . Like I said on success it return 200 and connection id but not on 4xx . 

```
function insertInterconnectAttachment(\Google_Client $client, $project_id, $region, array $body)
{
    $computeService = new \Google_Service_Compute($client);
    $interconnectAttachmentBody = new \Google_Service_Compute_InterconnectAttachment($body);
	//print_r($body);
	//print_r( $interconnectAttachmentBody);
    $result =$computeService->interconnectAttachments->insert(
        $project_id,
        $region,
        $interconnectAttachmentBody
    );

	return $result;
} 

$project_id = 'company-gcp-interconnect';
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->addScope(\Google_Service_Compute::COMPUTE);

$result = insertInterconnectAttachment(
    $client,
    $project_id,
    $region,
   [
  'name'=> $name,
  'bandwidth'=> $band_value,
  'pairingKey'=> $paring_key,
  'interconnect'=> $interconnect,
  'type'=> 'PARTNER_PROVIDER',
  'vlanTag8021q'=> $vlan,
  'partnerMetadata'=> [
    'interconnectName'=> $name,
    'partnerName'=> 'CompanyName',
    'portalUrl'=> 'https://company.com'
    ],
 ]
);

print_r($result);
```

**Comment by benderis** [comment]
One more thing, I delete attachment from gcp and after try to delete through web api and it return 404 error . 

`Fatal error: Uncaught Google_Service_Exception: { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "The resource 'projects/project-gcp-interconnect/regions/europe-west1/interconnectAttachments/testtttttrf' was not found" } ], "code": 404, "message": "The resource 'projects/project-gcp-interconnect/regions/europe-west1/interconnectAttachments/testtttttrf' was not found" } }`

So it won't return 4xx only on creating connection

**Comment by jdpedrie** [comment]
Unfortunately, due to the nature of interconnects, it's difficult for me to run and verify my answer, but based off my studying of the documentation, I may be able to offer some pointers.

The [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/interconnects/insert#response-body) indicate that the response is a long-running operation. In error cases, you may still receive a 200 status with an Operation. You should inspect the response (`Operation.error`) to find error messages.

If you are not receiving a response, your best option may to pose the question to the Compute team using one of the support methods described on their [Getting support](https://cloud.google.com/compute/docs/getting-support) page. If you have a support package, definitely make use of it to get help from the API team. If not, I'd suggest the google group.
