### ISSUE TITLE
One time login without save it session to browser

### ISSUE THREAD

**Issue by murzid** [googleapis/google-api-php-client#1635]
When login using Google Client, a session / cookie data of current user account is saved to the browser, how to prevent it (implement one time login without save it session / cookie to browser) ?

And Is there a function to logout from Google using Google Client API (clear logged user's session / cookie) ?

**Comment by jdpedrie** [comment]
Hi @murzid,

Can you share the code you're using? The client itself only handles providing auth tokens, not persistence. Are you following a tutorial or example which sets cookies?

**Comment by murzid** [comment]
```php
// Google Client
$client = new Google_Client();
$client->setApplicationName('MY APPS');
$client->setClientId('xxxxxxx.apps.googleusercontent.com');
$client->setClientSecret('xxxxxxxxxxxxxxxxxxxxxxx');
$client->setRedirectUri('http://domain.com/login');
$client->setAccessType('offline');
$client->setApprovalPrompt('force');
$client->setScopes([
	"https://www.googleapis.com/auth/userinfo.email",
	"https://www.googleapis.com/auth/userinfo.profile",
	"https://www.googleapis.com/auth/plus.me"
]);

// Google Auth URL
$url = $client->createAuthUrl();

// Login Link
echo '<a href="{$url}">Click here to login</a>';
```

After successfully entering the Google Account, we can automatically access all Google services (such as Gmail, photos, drives, etc.) on other browser tabs.

Even though what we want to do is just log in to the website http://domain.com, not to access Google services on other browser tabs.

After closing the browser and reopening it, and then logging into http://domain.com we are not asked to enter a Google Account again because the data has been stored in the browser (session / cookie created by Google).

Can this problem be prevented?

**Comment by jdpedrie** [comment]
Since you must be logged into a Google account to obtain an auth token for your application, the login status on Google is controlled by Google, not by your application. Unfortunately, there's not much you can do to change this as the application developer. Your users could mitigate this by using a private browser session, for instance (which would clear stored cookies once closed), though this would also impact the login state of your application.

I believe that should resolve the issue. If I've misunderstood or not fully answered your question, please reopen and we'll continue working on a solution. :)
