### ISSUE TITLE
changing 'consumptionState' for Google Play Billing purchase

### ISSUE THREAD

**Issue by bukssaayman** [googleapis/google-api-php-client#1636]
I just cannot find how to change the 'consumptionState' for a purchase. As far as I am aware, after successful processing the purchase I need to consume the purchase on Google Play Billing. What is the call I make to consume this purchase?

**Comment by jdpedrie** [comment]
The API to consume an in-app purchase is not included in the library's [API Services](https://github.com/google/google-api-php-client-services). However, if the Google Play Billing API supports HTTP, you can use this library by [Making HTTP Requests Directly](https://github.com/google/google-api-php-client#making-http-requests-directly).

Within your Android app, you can consume a product using the [Android Billing client](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#consumeasync)

**Comment by doom-goober** [comment]
@jdpedrie Being able to consume a purchase on the server through the API would be VERY nice. I'm on a node.js server and making the http request with a service account seems very hairy (the google api documentation actually discourages using http because the jwt is so hard to get right!)

Here's the use case: Client purchases product, server confirms product is valid and not consumed, server grants items, server marks product as consumed, and done. If the client tries to lie to the server and ask for the product again, the server will see it's marked consumed and reject it.

Without the ability to easily mark products as consumed on the server, the server now has to rely on the client to mark it as consumed, which is a security/cheater's nightmare.

Thanks.

**Comment by bshaffer** [comment]
I would suggest using the [`google/auth`](https://github.com/googleapis/google-auth-library-php) package to make an HTTP request to the consume endpoint. This is the official google auth library for PHP,  so it's recommended for use.

```php
$credentials = Google\Auth\ApplicationDefaultCredentials::getCredentials();
$http = Google\Auth\CredentialsLoader::makeHttpClient($credentials);
$http->request(
    'POST',
    'https://www.googleapis.com/androidpublisher/v3/applications/packageName/purchases/products/productId/tokens/token:consume',
    [
        'json' => [
            'param1' => 'val'
        ]
    ]
);
```

**Comment by apos-cadabra** [comment]
@bshaffer @doom-goober where did you get that the endpoint

https://www.googleapis.com/androidpublisher/v3/applications/packageName/purchases/products/productId/tokens/token:consume

exist?

**Comment by doom-goober** [comment]
> @bshaffer @doom-goober where did you get that the post to endpoint
> 
> https://www.googleapis.com/androidpublisher/v3/applications/packageName/purchases/products/productId/tokens/token:consume
> 
> exist?

The consume API seems to have vanished. This appears to be the new API:
https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/acknowledge

Dunno what happened to it. They are all v3.
