### ISSUE TITLE
Discontinuing support for JSON-RPC and Global HTTP Batch Endpoints

### ISSUE THREAD

**Issue by ngystvn90** [googleapis/google-api-php-client#1687]
This issue will be handled in a new release or we need to take action?

**Comment by DavydeVries** [comment]
I guess, we need take action because we got a mail. So it looks like that this library using the old batch endpoint?

**Comment by ngystvn90** [comment]
Yes, it uses the old batch endpoint. But maybe they will release a new version to fix this problem. It would be nice to know if we need to change the code or we will receive a fix.

**Comment by jdpedrie** [comment]
The Google API Client for PHP is compatible with the new batch endpoints starting at `google/apiclient-services` v0.86. Run `composer info` to verify that you have upgraded to a compatible version.

See [Discontinuing support for JSON-RPC and Global HTTP Batch Endpoints](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html) and scroll down to the section regarding the PHP Client Library for more details.

**Comment by DavydeVries** [comment]
So to clarify this issue, if you use this library with `v2.2.0` the composer file of this library contains `"google/apiclient-services": "~0.13"`.
With `~` before the version it allows to update to the highest version (example: `0.9999`, but not major like `1.xx`) [See composer docs for further explanation](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-).

So that allows to that [google/apiclient-service](https://github.com/googleapis/google-api-php-client-services) to update (currently) [v0.109](https://github.com/googleapis/google-api-php-client-services/tree/v0.109)

**Comment by jdpedrie** [comment]
That's correct. So long as you're not pinning to a very old version of `google/apiclient-services`, you're good to go.

**Comment by aaronhuisinga** [comment]
@jdpedrie We're currently using google/apiclient v2.4.1 and google/apiclient-services v0.136 and are seeing errors from the planned batch outage today (Global HTTP Batch endpoint is deprecated. See https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html for info and migration steps.)

We're only using the official Google API Client for making the batch requests, and aren't overriding the batch URL variable anywhere.

Is this a mistake on their end for the notifications during the planned outage today, or is there something that we might be doing wrong within our usage of these packages?

**Comment by mattlibera** [comment]
@aaronhuisinga Not sure if you've gotten past this yet, but...I was updating some old code and found this gem in the blog post, in the Java section:

> Please ensure you are creating your BatchRequest (i.e) com.google.api.client.googleapis.batch.BatchRequest instance via your **service client**.

This actually also applies to PHP. In my case we were instantiating the Batch object ourselves:

```php
$batch = new Google_Http_Batch;
```

With this I was still seeing this error even on latest version of all of the libraries. Turns out there is now a different way to instantiate the Batch off of the Service class, that is aware of the proper batch endpoint for that service:

```php
$service = new Google_Service_Directory($client);
$batch = $service->createBatch(); // this method will create a Google_Http_Batch and inject the proper service endpoint
```

Once you change that you should be able to `$batch->add()` and `$batch->execute()` just like normal.

Not sure if this is helpful, but it's something I just came across in some old code and had to dig to fix.

**Comment by aaronhuisinga** [comment]
@mattlibera That is exactly what we ended up changing as well!
