### ISSUE TITLE
Firebase cloudmessaging multi device sending

### ISSUE THREAD

**Issue by Yanlong-LI** [googleapis/google-api-php-client#1735]
Firebase cloudmessaging is sent by multiple devices. Does anyone know what I should do? Because there is no se tokens method

**Comment by jdpedrie** [comment]
Hello,

This repository is intended for help with specific questions related to the PHP API Client. We are not able to assist with general implementation questions.

I suggest you try posting your question to [Stackoverflow](https://stackoverflow.com/questions/tagged/firebase+firebase-cloud-messaging) (be sure to provide as much information as possible, and ask specific questions rather than general ones to avoid it being closed). You may also see whether any of the other [Firebase support channels](https://firebase.google.com/support) may be of assistance.
