### ISSUE TITLE
accept-language not supported

### ISSUE THREAD

**Issue by BusinessClick** [googleapis/google-api-php-client#1810]
Trying to get MyBusiness Location Reviews it seems that $optParams not support 'accept-language' variable for headers.

This causes review comments in an unexpected language (such arabic instead of english etc.).

If I force adding withHeaders accept-language variable all working greats.

**Comment by jdpedrie** [comment]
Hi @BusinessClick, sorry for the delayed response.

Could you share a bit more detail on how you're solving the problem? Sample code would be fantastic.

Unfortunately, since it doesn't appear the `accept-language` header is [documented as part of the request](https://developers.google.com/my-business/reference/rest/v4/accounts.locations.reviews/get), it's unlikely we'll be able to add it directly to `$optParams`, since that code is automatically generated. However, depending on how you're working around the issue, we may be able to improve things a bit!

**Comment by jdpedrie** [comment]
I'm going to close this issue out. If you're still having trouble, please feel free to re-open!
