### ISSUE TITLE
Unexplained rate limit exceeded error (403)

### ISSUE THREAD

**Issue by medinae** [googleapis/google-api-php-client#1819]
#### Environment details
  - PHP version: `7.2.28`
  - Package name and version: `google/apiclient 2.4.1`

#### Use case

Hello there, 
We are trying to integrate the _Youtube Live Streaming API_ to our backend. Everything is already implemented and we have already the full flow working properly :
_Create broadcast -> Create & Bind stream -> check stream status -> Transit to testing -> check broadcast status -> Transit to live -> Transit to end._

The problem we are facing is that every ~2 days, we are facing the `403 userRequestsExceedRateLimit 
 User requests exceed the rate limit.` error.

This seems really strange to us as we are not yet live with the feature, and we only have few people testing everyday, we are not doing more than 8/9 full live flows a day.
Also, we checked the Google Console API Usage reporting tool and we figured 
out that we were really far from reaching our daily limit.
We also heard about a per second limit, but we are not using the service intensively so we are mostly sure this could not be our issue (at Max i think we are doing 2/3 queries per second when creating stream/binding).

At some point we suspected a potential fraud detection service at Google doing some checks using the `User-Agent` header as we figured out the `php sdk` was building the requests user agent like : 
![image](https://user-images.githubusercontent.com/15857322/79639476-32c76b80-819d-11ea-9034-e6838cb51f14.png)

As we were not setting any application name, the generated User-Agent was ` google-api-php-client/2.4.1`. So If the fraud detection service is using User-Agents to do some checks, that means all the php sdk users that are using the same version than us and not setting the application name would perhaps be counted as one single "user".
So we tried to set a custom application name yesterday.

But we are still not convinced to have the good solution and we would like to make 100% sure we understand what is happing and how to mitigate the issue permanently.

Thanks a lot.
Please do not hesitate to ask me for me details if needed.

**Comment by jdpedrie** [comment]
Hi @medinae,

Unfortunately we don't have the tools to help with this issue here. This repository can help with problems specific to the client library, but I don't think that's the root cause. [This stackoverflow answer](https://stackoverflow.com/a/34865398/324307) contains some good tips which you may explore. The API team monitors the [`youtube-livestreaming-api`](https://stackoverflow.com/questions/tagged/youtube-livestreaming-api) tag on stackoverflow, so you should have some luck there if the solutions in the other link don't do the trick.

Best of luck, and if you have issues with the client itself, or find that this problem is indeed related to the library, please do let us know here.
