### ISSUE TITLE
id_token not an index in OAuth2.php

### ISSUE THREAD

**Issue by simoncast** [googleapis/google-api-php-client#183]
I keep seeing this error in my logs:

Undefined index: id_token in GoogleOauth2/src/Google/Auth/OAuth2.php on line 446 

I've updated to the latest code but the errors are continuing.

**Comment by mzmmlds** [comment]
i had the same problem, but i resolved to by passing id_token with verifyIdToken() function. Below is the complete code for reference.

if (Session::has('access_token')){ 
         $token = Session::get('access_token');
         
         $idToken = json_decode($token);
	 
         $token_data = $client->verifyIdToken($idToken->id_token)->getAttributes();
         $user_id = $token_data['payload']['sub'];
  	
         dd($user_id);
		    
         $client->setAccessToken($token);
}

i'm using laravel framework.

**Comment by judgej** [comment]
@mzmmlds Is this still working for you? The `$client->verifyIdToken($idToken->id_token)` statement for me is returning boolean `false` rather than an object. I'm guessing it isn't verifying for whatever reason, but https://jwt.io/ does decode the `idToken` correctly. Is there a way to decode it without verifying it?
