### ISSUE TITLE
setDescription() on JPEG file is ignored when file has an EXIF description

### ISSUE THREAD

**Issue by gicelte** [googleapis/google-api-php-client#1835]
Even though the description is set, it is ignored if JPG file has field Exif.Image.ImageDescription of metadata set.

In this case the file description will be the EXIF description.

How can I avoid that?

#### Environment details
  - OS: Linux
  - PHP version: 7.1.33
  - Package name and version: latest

#### Steps to reproduce

  1. Run code below on a JPEG file which has the Exif.Image.ImageDescription field set

#### Code example

```php
        $file = new Google_Service_Drive_DriveFile();        
        $file->setName($givenname);
        $file->setDescription($description);
        $file->setParents(array($folderid));
        $result = $this->_Gservice->files->create($file, array('data' => file_get_contents($filename),
                                                               'mimeType' => 'application/octet-stream',
                                                               'uploadType' => 'multipart'));
        (...)
        $optParams = array(
          'pageSize' => 1, // one file returned per call
          'orderBy' => 'createdTime desc',
          'fields' => 'nextPageToken, files(id, name, size, md5Checksum, description, parents)'
        );
        $results = $this->_Gservice->files->listFiles($optParams);
        $allfiles = $results->getFiles();
        $file = reset($allfiles); // get first element of array
        $descriptiongdrive = $file->getdescription(); // description is NOT the one which was set!
```

**Comment by jdpedrie** [comment]
I've verified the behavior you're reporting. While I know it's less than ideal, I have found that subsequent updates to the file allow you to set the description as desired. For instance, if you use the following after the sample code you provided:

```php
$this->_Gservice->files->update(
	$file->getId(),
	new Google_Service_Drive_DriveFile(['description' => $description])
);
```

Of course you may also find it better to strip the EXIF description from the image prior to uploading.

Unfortunately that's about as far as we can go here. This repository isn't monitored by the API team and it's intended for help with issues specific to the client library. I suggest opening a report in the [public issue tracker](https://issuetracker.google.com/issues?q=componentid:191650%20status:open) (since I believe there's an argument that the current behavior may be incorrect), or on [Stackoverflow](https://stackoverflow.com/questions/tagged/google-drive-sdk). Both those forums are monitored by the API team, who will be better equipped to provide more information or to update the API.
