### ISSUE TITLE
Different token for diff accounts

### ISSUE THREAD

**Issue by ashishkmishra95** [googleapis/google-api-php-client#1896]
I have a doubt can I add multiple user to Gmail API if not then can I have different tokens for different mail ID so that I can use it as multiple user please help me

**Comment by dwsupplee** [comment]
@ashishkmishra95 would you be able to add a little more information about your use case please? We'll try to help the best we can.

**Comment by ashishkmishra95** [comment]
> @ashishkmishra95 would you be able to add a little more information about your use case please? We'll try to help the best we can.

I have made my multiple user login account using multiple client api but now the problem is that how should I refresh my access token please can anyone one have a project file in php the. Mail me @ python.ashishmishra@gmail.com ...I want it in php

**Comment by bshaffer** [comment]
@ashishkmishra95 if you'd like to refresh your access token, store the access token in JSON format (along with the "refresh_token" which should have come back from the API when you set "access_type" to "offline". Also be sure to take a look at the [Authorization Code flow](https://github.com/googleapis/google-api-php-client/blob/master/examples/simple-file-upload.php) because this is needed to obtain a refresh token.

```php
$tokenPath = '/path/to/your_access_token.json';
$client = new Google_Client();
$client->setAccessType("offline");  // this is required to get a "refresh_token" back
$client->setAuthConfig('/path/to/client_secrets.json');  
$client->addScope(Google_Service_Gmail::GMAIL_SETTINGS_BASIC); // or whatever scope you need
if (!file_exists($tokenPath) {
   // Execute the authorization flow found in our other samples to request an access token with.
   // @see https://github.com/googleapis/google-api-php-client/blob/master/examples/simple-file-upload.php
}
$token = json_decode(file_get_contents($tokenPath));
$client->setAccessToken($token);

if ($client->isAccessTokenExpired()) {
    $refresh_token = $client->getRefreshToken();
    if (!empty($refresh_token)){
        $client->fetchAccessTokenWithRefreshToken($refresh_token);      
    }
}
```

**Comment by ashishkmishra95** [comment]
Ok sir now I understood all that how to use acces and refresh token but now
I have a doubt that how many time did I use refresh token to get updated
access token.... Is refresh token has update?? Please sir answer me this
question.

Thanks & Regards
Ashish Mishra

**Comment by bshaffer** [comment]
@ashishkmishra95 The code above will request a new access token every time the code is executed, because no caching is involved. Access tokens are good for 60 minutes, so you could potentially save the new access token to a file so that you don't keep requesting it over and over again. Something like this:

```php
if ($client->isAccessTokenExpired()) {
    $refresh_token = $client->getRefreshToken();
    if (!empty($refresh_token)){
        $token = $client->fetchAccessTokenWithRefreshToken($refresh_token);      
        // save the access token back to the file
        $token['refresh_token'] = $refresh_token;
        file_put_contents($tokenPath, json_encode($token)); 
    }
}
```
