### ISSUE TITLE
DisplayVideo's invalid targetingType

### ISSUE THREAD

**Issue by hoanguel** [googleapis/google-api-php-client#1950]
I am referring to this end-point:
```
https://developers.google.com/display-video/api/reference/rest/v1/advertisers.targetingTypes.assignedTargetingOptions/list
```
When calling:         
```
$service->advertisers_targetingTypes_assignedTargetingOptions->listAdvertisersTargetingTypesAssignedTargetingOptions($advertiserId, 'TARGETING_TYPE_GEO_REGION');
```
we always have this error:
```
{
"error": {
"code": 400,
"message": "The value \"TARGETING_TYPE_GEO_REGION\" is not valid for field \"targeting_type\".",
"errors": [
{
"message": "The value \"TARGETING_TYPE_GEO_REGION\" is not valid for field \"targeting_type\".",
"domain": "global",
"reason": "badRequest"
}
],
"status": "INVALID_ARGUMENT"
}
}
```

despite the fact that it is a valid value as documented here:
`https://developers.google.com/display-video/api/reference/rest/v1/TargetingType`

**Comment by bshaffer** [comment]
Hello! It looks like this API has been sunset and it's now recommended to [migrate to v2](https://developers.google.com/display-video/api/v2-migration-guide). Additionally, as this issue is over 2 years old, it's probably not relevant anymore, so I am closing it. I hope this helps and sorry for the inconvenience.
