### ISSUE TITLE
YouTube Data API returns no channel on “Playlists.list” but on “Channels.list”

### ISSUE THREAD

**Issue by ninsky** [googleapis/google-api-php-client#2026]
(This is a copy of [this Stackoverflow question](https://stackoverflow.com/questions/65576257/php-youtube-data-api-returns-no-channel-on-playlists-list-but-not-on-channel) I've posted yesterday)

I'm not sure if this is an inconsistency of YouTube's Data API or just a bad naming of a YouTube error. I'm using PHP API client v2.8.3.

There's a public channel on YouTube without any content:

https://www.youtube.com/channel/UCvAHk_1_TMmq6SW0XA9BcgA.

If I query Channels:list (query) with this channel ID UCvAHk_1_TMmq6SW0XA9BcgA, I get the following response:

```
{
  "items": [
    {
      "id": "UCvAHk_1_TMmq6SW0XA9BcgA",
      "snippet": {
        "title": "level10store0"
      },
      "status": {
        "privacyStatus": "public",
        "isLinked": true,
        "longUploadsStatus": "longUploadsUnspecified"
      }
    }
  ]
}
```
If I query for all playlists of this channel via Playlists:list (query) I get this response:

```
{
  "kind": "youtube#playlistListResponse",
  "etag": "iziRvpOe3rkNWHlySTxLgAk4dJI",
  "pageInfo": {
    "totalResults": 0,
    "resultsPerPage": 5
  },
  "items": []
}
```
But using YouTube's PHP client with Playlist:list you'll get a response error with following information:

`domain=youtube.playlist, reason=channelNotFound, location=channelId, locationType=parameter`

Why does YouTube's PHP client give a channelNotFound error instead of an empty response like YouTube's data explorer does?

**Update 1:**
YouTube's data API delivered a channel on the OAuth handshake initialized by the user itself. My application asked for an offline access token for further requests. If I use this access token I experience the above mentioned behaviour. I think the token is valid as I use the identical process for many other users. If the token would not be valid I would have got an error message like global.authError or youtube.header.youtubeSignupRequired.

My code looks like this (which works for many other users):

```
$youtubeClient->playlists->listPlaylists(
    'snippet,contentDetails',
     array(
        'maxResults' => 50,
        'channelId' => $channelId,
        'pageToken' => $nextPlaylistPageToken,
        'fields' => 'etag,items(id,etag,snippet(publishedAt,channelId,thumbnails/default,title),contentDetails(itemCount)),nextPageToken'
    )
);
```

**Comment by saranshdhingra** [comment]
Hi @ninsky 
First of all, I apologise for such a late response on the issue.

Perhaps your issue is long resolved by now.

But I did try the code snippet and also tried running the same on the [Youtube API reference](https://developers.google.com/youtube/v3/docs/playlists/list) page. I was not able to replicate the issue with or without using the `offline` grant type.

What I mean is the PHP library and the api reference page, both returned the same result. I get an empty array when I try to use the following:
```php
$service = new YouTube($client);
$playlists = $service->playlists->listPlaylists(
        'snippet,contentDetails',
         array(
            'maxResults' => 50,
            'channelId' => "UCvAHk_1_TMmq6SW0XA9BcgA",
            'fields' => 'etag,items(id,etag,snippet(publishedAt,channelId,thumbnails/default,title),contentDetails(itemCount)),nextPageToken'
        )
);

var_dump($playlists->getItems());
```

I don't see the `channelNotFound` error that you mentioned.

Please let me know if this was resolved for you or did you circumvent this at the time.
Thanks for the patience.

**Comment by ninsky** [comment]
Hello @saranshdhingra 

Thanks for your reply! My application performs thousands of requests per day. Currently I don't have the time to see whether this error still occurs. But I will come back to this issue in case I can reproduce it.

BR
ninsky

**Comment by shreyjain362** [comment]
A similar issue is again seen. The [YouTube API Reference](https://developers.google.com/youtube/v3/docs/playlists/list) page returns Channel Not Found for any public channel when we specify ChannelId. 
And the python API behaves like mine=True when we use channelId=<something> . There is a bug there too.

**Comment by bshaffer** [comment]
This issue is in reference to the PHP client library. You can file an issue for the python client [here](https://github.com/googleapis/google-api-python-client/issues).

If you're seeing the issue on the APIs explorer, PHP client, AND python client, then it's unlikely the issue is in the client libraries (which is what we cover), and instead is an API Usage issue. I'd suggest asking your question on stack overflow instead.
