### ISSUE TITLE
404 error while accessing client json file from php client library

### ISSUE THREAD

**Issue by sujeeshskn** [googleapis/google-api-php-client#2043]
Hi,

I am developing web application for accessing google reviews by using google my business API. My programming language is PHP.
PHP client library used for getting account information. But when accessing google credential.json file from php client library, I am facing 404 error. Initially json file was placed incode library folder in same location where accessing it. Same error was there.

So I placed json file inside public folder of my project. Even in this situation itself, its showing 404 error.

I am stuck on this. Can anyone give me support on this ?
What may be went wrong here.

Followup Email ID: [4-3050000031171]

Waiting for a positive response.

Sujeesh
![client_json_error](https://user-images.githubusercontent.com/55076871/107183112-24845d80-6a04-11eb-9390-a827f7809fa3.png)

**Comment by jdpedrie** [comment]
You are using `Google\Client::setAuthConfig()` with the path to your credentials.json file?

First, do not place the credentials file in a public folder. This will allow anyone to view your credentials. Second, it seems as though the path you are providing to `setAuthConfig()` is incorrect. Since this path is specific to your application and web server, we can't tell you what it is. You will need to figure that out yourself. You can run `echo __DIR__;` in a PHP file to view the absolute path to that file. That should help you determine the path to your credentials file.

**Comment by sujeeshskn** [comment]
Hi,

Thank you so much for your comments. Defenitely I will try this.

**Comment by josiahke** [comment]
you are using laravel

copy the JSON file into "storage/app/google-analytics/ddfdfdfdf.json"

read file 

$client = new Google_Client();
$client->setApplicationName("your app");
$client->setAuthConfig(storage_path("app/google-analytics/ddfdfdfdf.json"));

**Comment by yash30201** [comment]
Hi @sujeeshskn , I hope the above pointers helped you and thus closing this issue.

Please feel free to reopen incase you are still struck on this.
