### ISSUE TITLE
Internal Error when copying a sheet into a different Spreadsheet

### ISSUE THREAD

**Issue by realtebo** [googleapis/google-api-php-client#2048]
#### Environment details

  - OS: Debian 10.6
  - PHP version: 7.3
  - Package name and version: google-api-php-client, latest versione

#### Steps to reproduce

I created a sheet
I created a 2nd sheet
I created a service account
I sharead r/o the first sheet with service account
I sharead r/w the second sheet with service account

#### Code example

```php
        $source_file_id = config('google_sheets.shops_source_file_id');
        $destination_file_id = config('google_sheets.shops_file_id');
        $sheet_index = 0;
        $copy_sheet_request = new \Google_Service_Sheets_CopySheetToAnotherSpreadsheetRequest();
        $copy_sheet_request->setDestinationSpreadsheetId($destination_file_id);
        $response = $this->service->spreadsheets_sheets->copyTo(
            $source_file_id,    
            $sheet_index,
            $copy_sheet_request
        );
```

### Results

Google\Service\Exception
{ "error": { "code": 500, "message": "Internal error encountered.", "errors": [ { "message": "Internal error encountered.", "domain": "global", "reason": "backendError" } ], "status": "INTERNAL" } }

**Comment by dwsupplee** [comment]
@realtebo We're not experts on each API offered, but rather on the client libraries which help interact with them - so this may not be the best place to get resolution. I'd recommend reaching out to the [support staff](https://developers.google.com/sheets/api/support) for the API as it looks like this isn't related to the client itself (but please let me know if you find otherwise and we can re-open!).

**Comment by appimatic** [comment]
whenever I see a google api 500 error with "domain": "global", "reason":
"backendError" it is almost always a transient error having nothing to do
with my code. I have seen these last for up to a week before subsiding
(Google Sheets PHP API) and no code changes on my part.

you might also see it when you perform the API sequences out of order, or
otherwise illogically.

**Comment by realtebo** [comment]
I hoped it was a transient error but it is still here !
I know it's not due to your package, I simplu hope that the team of this package has some internal contacts with api service developes.
Sigh.
