### ISSUE TITLE
return null why

### ISSUE THREAD

**Issue by khanhnam99** [googleapis/google-api-php-client#2101]
$key = public_path().'/cmsmrtho-firebase-adminsdk-jhhpo-ac662abbc0.json';
        $client = new \Google_Client();
        $client->setApplicationName('Play Cool Math Notifications');
        $client->setAuthConfig($key);
        $client->addScope('https://www.googleapis.com/auth/firebase.messaging');
        $client->authorize();
        $token = $client->getAccessToken();
        echo $token;

     // it return null why ?

**Comment by khanhnam99** [comment]
![image](https://user-images.githubusercontent.com/575720/124710587-2d337e00-df27-11eb-8bba-31d8cda81425.png)

**Comment by saranshdhingra** [comment]
Hi @khanhnam99 
Sorry for a very late reply on this.

But from what I can see from the source of the `Client` class, because you have supplied a key in the [setAuthConfig](https://github.com/googleapis/google-api-php-client/blob/c73bdc5734425455f748c134b53598a34e9a4735/src/Client.php#L984) method, those credentials are used as default credentials.

After this, in the [authorize](https://github.com/googleapis/google-api-php-client/blob/c73bdc5734425455f748c134b53598a34e9a4735/src/Client.php#L419) method, the credentials are attached to the auth handler, which is returned to you in the `authorize` call. So, the access token is never set for the `Client` class.

So you can make the calls like so:
```
$httpClient = $client->authorize();
$response = $httpClient->get('https://www.googleapis.com/auth/firebase.messaging');
```

Hope this answers your question.
