### ISSUE TITLE
Missing title field when uploading file

### ISSUE THREAD

**Issue by exstreme** [googleapis/google-api-php-client#2141]
#### Environment details

  - OS:does not matter
  - PHP version:all
  - Package name and version:latest

#### Steps to reproduce

I'm trying to send a file to google analytics, but through the SDK there is no way to transfer the file name, while using an example in Javascript - there is such an opportunity. I think the differences in the use of different SDKs are imbalanced, while the function is really useful.

#### Code example

https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/uploads/uploadData?hl=ru#php

**Comment by LindaLawton** [comment]
This is a known issue on the Google analytics api. It has to do with how the file name is posted.

**Comment by exstreme** [comment]
> This is a known issue on the Google analytics api. It has to do with how the file name is posted.

Yes, I know. However, this issue has not been corrected for more than 5 or 10 years.
Bit this feature is very useful.

**Comment by LindaLawton** [comment]
Find the issue on the [issue tracker](https://issuetracker.google.com/issues?q=componentid:187400) and add your name to it.  Thats the only way to get the Google analytics team to fix it.

Its not something that can be fixed in this library sadly it effects all the libraries because its an issue in Google analytics api itself.

**Comment by exstreme** [comment]
> Find the issue on the [issue tracker](https://issuetracker.google.com/issues?q=componentid:187400) and add your name to it. Thats the only way to get the Google analytics team to fix it.
> 
> Its not something that can be fixed in this library sadly it effects all the libraries because its an issue in Google analytics api itself.
> 
> TBH i think you are only the second or third person i have heard from that has noticed it :)

Why is there an opinion that the problem is in api? I can safely set the file name without the library, but I want to use the SDK for these purposes. So why isn't the problem with the library then?

**Comment by exstreme** [comment]
https://issuetracker.google.com/issues/35353754

**Comment by LindaLawton** [comment]
I that issue https://issuetracker.google.com/issues/35353754 google blames the libraries. 

>Hi Thanks for writing in. This is an issue we are aware of and a consequence of the client libraries stripping the filename from POST body information. CURL can be used to upload a file and the filename remains in the POST body and it will be preserved in the UI.

I found this one on the .net client library which explains why they wont fix it https://github.com/googleapis/google-api-dotnet-client/issues/1087

I really think you should try to find a work around and go with that.

**Comment by LindaLawton** [comment]
@exstreme  So I pinged someone on the team.  This is a synopsis of the response I got from them.

It seams there is little they feel they can do to change Universal Analytics client libraries at this point.  Currently GA4 is the primary focus of development.  Its probably more likely that this functionality to appear in GA4, rather than being fixed in UA.

I did ask him to please put a note on that issue for others like you wondering how to deal with the issue.

**Comment by exstreme** [comment]
@LindaLawton thanks a lot

**Comment by bshaffer** [comment]
@LindaLawton thank you so much for your great insight into this issue.

I'm closing this as I believe the question to be answered and there is no other action to be taken.
