### ISSUE TITLE
Where are Google Pay-related classes defined? (Class not found)

### ISSUE THREAD

**Issue by GarrettAlbright** [googleapis/google-api-php-client#2176]
I'm trying to use this code to create a Google Pay loyalty pass and having a really hard time. The documentation seems incomplete and very scattered.

At the very beginning, code samples telling me to do, for example, `new Google_Service_Walletobjects_LoyaltyClass()` are failing with "Class 'Google_Service_Walletobjects_LoyaltyClass' not found" errors. Grepping the code base confirms no such class actually exists.

I found [this repository](https://github.com/ampsand/google-play-passes) where such classes *are* defined, but none of the documentation I've seen has indicated that this other repo/package is required, and additionally it's unclear if that's even an "official" Google package - it doesn't particularly look like one.

Thanks in advance for any help and insight you can provide.

**Comment by quinncomendant** [comment]
The *Google Wallet API PHP Client Library* is not included in the *Google APIs Client Library for PHP*, but you can download it on the [Google Wallet Client libraries page](https://developers.google.com/wallet/generic/resources/libraries#php).

The library isn't currently set up to use Composer's PSR autoloading (at least I couldn't get it working) so you can just manually include the `Walletobjects.php` file and reference the class names as, e.g., `$this->service = new \Google_Service_Walletobjects($this->client);`.

You can find instructions for using it in the docs for [Google Wallet Web API](https://developers.google.com/wallet/generic/web/prerequisites).

I agree that is is very confusing, and the Google APIs people need to collaborate with the Wallet API people so that these two libraries work better together. [This issues](https://github.com/googleapis/google-api-php-client/issues/1486) requests adding Walletobjects.php to the google-api-php-client, which I think is a good idea.

**Comment by bshaffer** [comment]
Thank you for the good info @quinncomendant! For some reason, the Google Wallet team has not published their API as part of the [Discovery API](https://discovery.googleapis.com/discovery/v1/apis), which means it won't be generated here. We can reach out to their team and see if they have any plans to add it, at which point it would be available as part of this library.

**Comment by GarrettAlbright** [comment]
For the record, I ended up just not using a library and using cURL (or maybe Guzzle; it's been a while) to make calls to the API directly.
