### ISSUE TITLE
require(/var/www/vendor/composer/../../src/aliases.php): failed to open stream

### ISSUE THREAD

**Issue by kanohn** [googleapis/google-api-php-client#2221]
I'm trying to use the google api index, but when i call:
require_once 'vendor/autoload.php';

I got error on my nginx log error:

> FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/vendor/composer/../../src/aliases.php): failed to open stream: No such file or directory in /var/www/vendor/composer/autoload_real.php on line 71PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/vendor/composer/../../src/aliases.php' (include_path='.:/usr/share/php') in /var/www/vendor/composer/autoload_real.php on line 71"

i'm using the latest version of api, also i tried to composer install, and tested with vendor folder installed by composer, got the same error.

I tried the version 2.5.0 too and this error doesn't happen but i got other error with Google Service.

How can i fix this?

**Comment by bshaffer** [comment]
I downloaded the latest release for PHP 7.4, and verified the class `src/aliases.php` exists. The error you're receiving must be due to your webserver not being able to read the file (either because it doesn't exist, or it has the wrong permissions). 

I am closing this because I do not believe the error here is in the library (as I was able to verify the file exists). If you can provide evidence that the file does not exist in one of our packages, please reopen or file a new bug.
