### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Google\Service\Drive\DriveFile::getHeaderLine() in ./vendor/google/apiclient/src/Http/MediaFileUpload.php:310

### ISSUE THREAD

**Issue by ckouris84** [googleapis/google-api-php-client#2272]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: CentOS
  - PHP version: 7.2
  - Package name and version:  "google/apiclient": "^2.10"

#### Steps to reproduce

  1. composer install 
  2. execute the following code that uploads large files to Google Drive
  3. fails with:
  
  Fatal error: Uncaught Error: Call to undefined method Google\Service\Drive\DriveFile::getHeaderLine() in ./vendor/google/apiclient/src/Http/MediaFileUpload.php:310

#### Code example

```php
		$gfmeta = new Google_Service_Drive_DriveFile();
		$gfmeta->name = $backupFileName;
		$gfmeta->parents = array($GoogleDriveBackupParentFolderID);
		$backupFilePath = dirname(__FILE__) . "/".$backupFileName;

		// Call the API with the media upload, defer so it doesn't immediately return.
		$GoogleClient->setDefer(TRUE);
		$guploadRequest = $GoogleDriveApp->files->create($gfmeta);

		// Create a media file upload to represent our upload process
		$media = new Google_Http_MediaFileUpload(
			$GoogleClient,
			$guploadRequest,
			mime_content_type($backupFilePath),
			NULL,
			TRUE,
			$GoogleDriveUploadChunkSizeBytes
		);
		$media->setFileSize(filesize($backupFilePath));
		
		// Upload the various chunks. $uploadStreamStatus will be false until complete
		$uploadStreamStatus = FALSE;
		$backupFileHandle = fopen($backupFilePath, "rb");
		while(!$uploadStreamStatus && !feof($backupFileHandle)) {
			$fileChunk = readFileChunk($backupFileHandle, $GoogleDriveUploadChunkSizeBytes);
			$uploadStreamStatus = $media->nextChunk($fileChunk);
		}
		// Take care of the file handle and file creation in Google
		$GoogleClient->setDefer(FALSE);
		fclose($backupFileHandle);

		// The final value of $uploadStreamStatus will be the data from the API for the upload
		$result = FALSE;
		if($uploadStreamStatus !== FALSE) {
				$result = $uploadStreamStatus;
		} else {
		#		throw new Exception("Upload Error!");
		}		

?>
```

NOTE:
I had to copy an outdated version of the Google PHP SDK repo to get the job done...which is not good.

**Comment by bar2** [comment]
I just experienced the same error on v2.12.5 Ubuntu 18.04 with PHP 7.3

**Comment by jon5477** [comment]
This is an issue with the latest release (v2.12.5) and is not present in the previous version (v2.12.4). This should be a very simple fix and I'll include the details on how to fix this here.

This line was changed in this [Pull Request](https://github.com/googleapis/google-api-php-client/pull/2252/files) and is the root cause of this error:
`$response = $this->client->execute($this->request, null);`
Reference: https://github.com/googleapis/google-api-php-client/blob/94e1964a7e0fd848eafdb1b485e0b68b9b5f08f1/src/Http/MediaFileUpload.php#L309

This line should actually be:
`$response = $this->client->execute($this->request, false);`

Passing `false` is actually the correct behavior in order to have the doExecute and decodeHttpResponse function return a Guzzle `Response` instead of a `DriveFile`. This is evident in the following line:
https://github.com/googleapis/google-api-php-client/blob/94e1964a7e0fd848eafdb1b485e0b68b9b5f08f1/src/Http/REST.php#L159

**Comment by bshaffer** [comment]
Thank you all for reporting this (and to @jon5477 for identifying the cause). Please check out [v2.12.6](https://github.com/googleapis/google-api-php-client/releases/tag/v2.12.6) see if your issue is now resolved

**Comment by jon5477** [comment]
I can confirm the issue is fixed. Thanks for fixing it.
