### ISSUE TITLE
Composer PHP requirement is effectively 8.1.1

### ISSUE THREAD

**Issue by jamesjohnmcguire** [googleapis/google-api-php-client#2302]
The documentation states that the PHP requirements are for 5.6 and above.  But because of the dependency package, monolog, which has a requirement of PHP 8.1.1, making the actual PHP requirement for this package at 8.1.1, as well, if my understanding is correct.

Updating the documentation may help reduce some confusion on the matter.

If my understanding is not correct, please let me know how to get this to work with PHP 7.4, etc.  By default, I am using PHP 8.1.1, so this isn't really a big issue for me.

#### Environment details

  - OS: Linux, Windows
  - PHP version: 7.4.3
  - Package name and version: monolog: 3.2.0

#### Steps to reproduce

  1.  composer install
  2. review composer.lock file
  3. at the monolog node, it has the following:
  
            "name": "monolog/monolog",
            "version": "3.2.0",
            ...
            "require": {
                "php": ">=8.1",
           ...

Additional example:  Running this script from the command line:
\Util\xampp.74\php\php SourceCode\vendor\bin\phpcs -sp --standard=ruleset.xml SourceCode

Will generate the following message:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.3. in \vendor\composer\platform_check.php on line 24

**Comment by bshaffer** [comment]
Composer will try to install the most up-to-date dependencies allowed for your environment and your package constraints. When you installed your dependencies, composer (for some reason unknown to me) decided that you were running PHP 8.1, and so pulled down a version of monolog only compatible with PHP 8.1 (v3.2.0).

As you can clearly see in our `composer.json`, we allow for versions of monolog 1, 2, and 3:

```
"monolog/monolog": "^1.17||^2.0||^3.0",
```

So yes, this library does support PHP 5.6 and above. The problem is that you are installing the wrong packages for your platform, and that is not the fault of this library, but in your environment.

**Comment by jamesjohnmcguire** [comment]
Thanks for explanation.

I was attempting to alternate between different versions of PHP for testing purposes.  It appears that it's going to be a bit more complex then simply calling the different version PHP executables.

**Comment by bshaffer** [comment]
Youll most likely want a different set of dependencies per PHP version. This is easy to do using version constraints in your composer.json. then you can run "composer update" on each platform.
