### ISSUE TITLE
Page crashes when calling listCalendarList()

### ISSUE THREAD

**Issue by peterwesterlund** [googleapis/google-api-php-client#2317]
I have installed everything without problem and created a Project and Service Account at Google Cloud. I've followed every steps in documentations that I can find to set up everything correctly.

But the site **crashes** when I'm trying to run this script to just get a list of the calendars in my calendar list:

```
if ($credentials_file = "example-123456789.json") {
    // set the location manually
    $client->setAuthConfig($credentials_file);
} elseif (getenv('GOOGLE_APPLICATION_CREDENTIALS')) {
    // use the application default credentials
    $client->useApplicationDefaultCredentials();
} else {
    echo 'Problem with credentials';
    return;
}

$client->setApplicationName("my-project");
$client->setScopes(['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar']);
$service = new Google\Service\Calendar($client);
$calendarList = $service->calendarList->listCalendarList();
```
The site does not crash when commenting away the last row where it is calling `listCalendarList()`. In fact, just even removing that call to listCalendarList() and leave that row like `$calendarList = $service->calendarList;` works. So it's something about calling `listCalendarList()` that causes the problem.

I don't even get an error message or anything. The page just crashes. What's the problem here?

**Comment by MatthewW1020** [comment]
I ran into a similar issue when performing some testing. I don't know if yours is the same but I would get an error if there was not a valid access token. I was studying the scenario when a user would revoked it from the Google Security page instead of my application. 

If they remove it from Google, your program may not know about this condition and when grabbing the listCalendarsList() is when it fails.  

`    try {
      $calendarList = $service->calendarList->listCalendarList();
    } catch (Exception $e) {
      error_log("Error with listCalendarList: $e");
      return(false);
      // Fix an invalid key or stop the execution
      // exit();
    } `

**Comment by MoleInteractive** [comment]
I fix the problem using a while, but you need to verify the scopes access in your app. May be it works for you.

 $service =  new \Google\Service\Calendar($client);
        $calendarList = $service->calendarList->listCalendarList();

        while (true) {
            foreach ($calendarList->getItems() as $calendarListEntry) {
                echo $calendarListEntry->getSummary();
            }
            $pageToken = $calendarList->getNextPageToken();
            if ($pageToken) {
                $optParams = array('pageToken' => $pageToken);
                $calendarList = $service->calendarList->listCalendarList($optParams);
            } else {
                break;
            }
        }

**Comment by saranshdhingra** [comment]
Hi @peterwesterlund 
Apologies for the delayed response on this.

I did try your code, i.e.
```php
$client->setScopes(['https://www.googleapis.com/auth/calendar.readonly','https://www.googleapis.com/auth/calendar']);
$service = new Google\Service\Calendar($client);
$calendarList = $service->calendarList->listCalendarList();
```

But I didn't receive any error.

Like @MatthewW1020 mentioned, it maybe possible due to an expired access token.

If you're still getting this error, please feel free to reopen this issue. We'll definitely take a closer look :)
