### ISSUE TITLE
I am unable to install this on PHP 8.0.26 - version not compatible

### ISSUE THREAD

**Issue by Abdullah-Iftikhar** [googleapis/google-api-php-client#2376]
composer require google/cloud
composer require google/apiclient

During installation, this gives me the error of version not compatible. Is there any good news about it the installation of PHP 8?

![image](https://user-images.githubusercontent.com/53434692/216231517-3c55c0f9-e624-4d44-85f8-a1f264c7d0a2.png)

**Comment by tben** [comment]
So I'm not the developer of this package. Saw your issue and wanted to help. So the message actually points you to the problem and that is within your own composer.json file for your project. Look for a line `"php":"^7.3"` and change it to `"php":"^7.3|^8.0"`.

**Comment by saranshdhingra** [comment]
Hi @Abdullah-Iftikhar 
As @tben mentioned, the problem seems to be with the version of PHP requested in your `composer.json` file.

The api client's [composer.json](https://github.com/googleapis/google-api-php-client/blob/main/composer.json#L9) already has a PHP version constraint of `^5.6|^7.0|^8.0`.

Just to verify manually, I even tried the set of commands you mentioned for a PHP version of `8.1.10` and everything worked fine.

I'll be closing this issue for now, but please feel free to reopen if you need more help.
Thanks
