### ISSUE TITLE
upload large file

### ISSUE THREAD

**Issue by danielezerosi** [googleapis/google-api-php-client#2411]
I'm using the example file and it works. I created OAuth and enabled two users for tests. But file is loaded on the google drive of the user who is using the functionality. I'd like to send file always to one google drive (where i registered the project).
Is it because project is still in test mode or i have to change some code ? and what do i have to change?

**Comment by bshaffer** [comment]
There may be a way to do this by sharing a drive folder with a service account (see [this blog post](https://www.labnol.org/google-api-service-account-220404) for more information). This is not a question regarding this library, and is more a usage question regarding Google Drive, so I am closing the issue here. You may have better luck asking a question like this on Stack Overflow.
