### ISSUE TITLE
https://googleapis.github.io/google-api-php-client/main/ is 404

### ISSUE THREAD

**Issue by ZdejPoham** [googleapis/google-api-php-client#2415]
Link to reference documentation is wrong.

**Comment by bshaffer** [comment]
Thank you for reporting this!
Looks like our docs generation script was not failing when there was an error, and as a result, an empty `gh-pages` was being published

I've at least fixed the issue so that it won't overwrite our docs site when there's an error (see https://github.com/googleapis/google-api-php-client/commit/7bac7a5b8710962e05c376a40b8216393ce2fe6d), which worked when it was published (see https://github.com/googleapis/google-api-php-client/actions/runs/4495597156/jobs/7909380673)

Now we just need to fix the error itself.

As I've reverted the publishing error in https://github.com/googleapis/google-api-php-client/commit/87daf6dc1b92b4f78d428247b8c200a4c427def1, and ensured it won't happen again in 7bac7a5b8710962e05c376a40b8216393ce2fe6d, this is now fixed.
