### ISSUE TITLE
error 400 : "Media type 'application/json; charset=UTF-8' is not supported."

### ISSUE THREAD

**Issue by afsh7n** [googleapis/google-api-php-client#2436]
Hello, have a good time, I use Google api v3 to upload videos to YouTube. Unfortunately, I am facing this error since yesterday without any changes in the code or the server.

I searched the error text in different parts, but I didn't get any results. The only thing I found is that inside this package and this file at this address src/Http/MediaFileUpload.php
The content-type is specified, whose value is application/json; charset=UTF-8 is set. I guess this is the problem. Please guide me.

Thank you

#### Environment details

  - OS: Linux
  - PHP version: 8.1.8
  - Package name and version: "google/apiclient": "^2.13.2"
 - Laravel : ^9.0
 - 
#### Steps to reproduce

``
  "error": {
    "code": 400,
    "message": "Media type 'application/json; charset=UTF-8' is not supported. ",
    "errors": [
      {
        "message": "Media type 'application/json; charset=UTF-8' is not supported. ",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
``

#### Code example

```php
 $chunkSizeBytes = 15 * 1024 * 1024;
        $client->setDefer(true);
        $insertRequest = $youtube->videos->insert("status,snippet,recordingDetails", $video , [
            'notifySubscribers' => true
        ]);
        $media = new MediaFileUpload(
            $client,
            $insertRequest,
            'video/'.File::extension($videoPath),
            null,
            false,
            $chunkSizeBytes
        );
        $media->setFileSize(File::size($videoPath));

        $status = false;
        $handle = fopen($videoPath, "rb");
        while (!$status && !feof($handle)) {
            $chunk = fread($handle, $chunkSizeBytes);
            $status = $media->nextChunk($chunk);
        }
        fclose($handle);

        $client->setDefer(false);
```

**Comment by bshaffer** [comment]
Hello. I see you've also [asked this question on Stack Overflow](https://stackoverflow.com/questions/76198408/error-400-media-type-application-json-charset-utf-8-is-not-supported). 

Looking at the code, the media type `application/json` happens when `$resumable` is false (see [here](https://github.com/googleapis/google-api-php-client/blob/main/src/Http/MediaFileUpload.php#L273) and [here](https://github.com/googleapis/google-api-php-client/blob/main/src/Http/MediaFileUpload.php#L239)).

So I would try setting `$resumable = true` (which is the fifth argument to `MediaFileUpload`). You can see an example of this in [`large-file-upload.php`](https://github.com/googleapis/google-api-php-client/blob/main/examples/large-file-upload.php).
