### ISSUE TITLE
refresh_token not return 

### ISSUE THREAD

**Issue by lRafaelOliveira** [googleapis/google-api-php-client#2519]
eu usava o a lib para autenticar com oauth2, funcionava bem até ontem... porem hoje, quando faço a autenticacao:
$client->fetchAccessTokenWithAuthCode($dados->code)

recebo um array com as info: 
Array
(
    [access_token] => ya2
    [expires_in] => 3599
    [scope] => www....
    [token_type] => Bearer
    [created] => 1700232993
)

o fato é que anteriormente me retornava nesse array, o refesh_token, que eu utilizava para poder atualizar o meu token de acesso.  

alguem sabe o que aconteceu? ou como obter o token de acesso ?

**Comment by bshaffer** [comment]
Hello @lRafaelOliveira 

The refresh token is only returned with the auth code when the "access type" is set to "online". You will need to do something like this to make sure you receive a refresh token:

```php
$client->setAccessType('offline');
```

This needs to happen _before_ you receive the authorization code, however, so that `access_type=offline` appears in the query string of the request to get the authorization code. For instance:

```php
$client = new Google\Client();
$client->setAuthConfig('client_secret.json');
$client->addScope(Google\Service\Drive::DRIVE_METADATA_READONLY);
$client->setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . '/oauth2callback.php');
$client->setAccessType('offline');        // offline access
$authUrl = $client->createAuthUrl();
```
and then in your HTML:

```
<a href="<?= $authUrl ?>" connect me! </a>
```

See the [simple file upload](https://github.com/googleapis/google-api-php-client/blob/main/examples/simple-file-upload.php) example for a full example.
