### ISSUE TITLE
documentation example of file resumable upload

### ISSUE THREAD

**Issue by momox-maxim** [googleapis/google-api-php-client#2526]
Hi,
could you please check if this example is outdated? It seems that it can not work

https://github.com/googleapis/google-api-php-client/blob/7a95ed29e4b6c6859d2d22300c5455a92e2622ad/examples/large-file-upload.php#L104

![image](https://github.com/googleapis/google-api-php-client/assets/124882639/2e15b89e-78ed-4a64-8802-2958c8d480fa)

**Comment by saranshdhingra** [comment]
I just tried it and seems to me that it is working just fine.
I don't know if the docbloc changed, I'll check and get back to you on that, but the code snippet is surely working fine.

**Comment by saranshdhingra** [comment]
Hi @momox-maxim 
I checked and the dobloc doesn't seem to be updated in a while and before we go further, I wanted to ask you did you use the `$client->setDefer(true);` part of the sample in your code.

I ask because I don't see that in the screenshot and using that line should mean that the `files->create` call should return an object that implements the `RequestInterface` meaning there won't be an issue with this.

**Comment by saranshdhingra** [comment]
Closing this issue for now.

Please feel free to reopen if more discussion on this is needed.

Thanks,
